{"status":"TESTS_FAILED","testResults":[{"name":"test.test_areas_of_shapes.AreasOfShapes.test_empty","successful":true,"message":"","valgrindFailed":false,"points":["p01-07.1"],"exception":[]},{"name":"test.test_areas_of_shapes.AreasOfShapes.test_many_queries","successful":false,"message":"314.0 !\u003d 314.1592653589793 within 4 places (0.1592653589793258 difference) : Wrong area for circle with radius 10!","valgrindFailed":false,"points":["p01-07.1"],"exception":["  File \"/home/nikolai/anaconda3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n","  File \"/home/nikolai/anaconda3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n","  File \"/home/nikolai/Documents/learning/datascience_mooc/exercises/tmcdata/TMC workspace/Exercises/hy/hy-data-analysis-with-python-2020/part01-e07_areas_of_shapes/test/test_areas_of_shapes.py\", line 57, in test_many_queries\n    self.assertAlmostEqual(float(m.group(1)), math.pi*10**2, places\u003d4, msg\u003d\"Wrong area for circle with radius 10!\")\n","  File \"/home/nikolai/anaconda3/lib/python3.7/unittest/case.py\", line 906, in assertAlmostEqual\n    raise self.failureException(msg)\n"]},{"name":"test.test_areas_of_shapes.AreasOfShapes.test_one_query","successful":true,"message":"","valgrindFailed":false,"points":["p01-07.1"],"exception":[]}],"logs":{}}