{"status":"TESTS_FAILED","testResults":[{"name":"test.test_merge.Merge.test_calls","successful":true,"message":"","valgrindFailed":false,"points":["p01-09.1"],"exception":[]},{"name":"test.test_merge.Merge.test_first","successful":false,"message":"Lists differ: [1, 1, 1, 1, 5, 9, 12] !\u003d [1, 2, 5, 6, 9, 10, 12]\n\nFirst differing element 1:\n1\n2\n\n- [1, 1, 1, 1, 5, 9, 12]\n+ [1, 2, 5, 6, 9, 10, 12] : Not correct result for input lists [1, 5, 9, 12] and [2, 6, 10]!","valgrindFailed":false,"points":["p01-09.1"],"exception":["  File \"/home/nikolai/anaconda3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n","  File \"/home/nikolai/anaconda3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n","  File \"/home/nikolai/Documents/learning/datascience_mooc/exercises/tmcdata/TMC workspace/Exercises/hy/hy-data-analysis-with-python-2020/part01-e09_merge/test/test_merge.py\", line 33, in test_first\n    self.assertEqual(result, sorted(L1+L2), msg\u003d\"Not correct result for input lists %s and %s!\" % (L1,L2))\n","  File \"/home/nikolai/anaconda3/lib/python3.7/unittest/case.py\", line 852, in assertEqual\n    assertion_func(first, second, msg\u003dmsg)\n","  File \"/home/nikolai/anaconda3/lib/python3.7/unittest/case.py\", line 1058, in assertListEqual\n    self.assertSequenceEqual(list1, list2, msg, seq_type\u003dlist)\n","  File \"/home/nikolai/anaconda3/lib/python3.7/unittest/case.py\", line 1040, in assertSequenceEqual\n    self.fail(msg)\n","  File \"/home/nikolai/anaconda3/lib/python3.7/unittest/case.py\", line 693, in fail\n    raise self.failureException(msg)\n"]},{"name":"test.test_merge.Merge.test_non_mutating","successful":true,"message":"","valgrindFailed":false,"points":["p01-09.1"],"exception":[]},{"name":"test.test_merge.Merge.test_random","successful":false,"message":"0 !\u003d 30 : Incorrect length of result list for input lists [-100, -100, -93, -90, -69, -61, -58, -49, -45, -22, -17, -8, -5, 0, 2, 34, 45, 84, 92, 98] and [-100, -68, -55, -2, 27, 32, 57, 69, 87, 99]!","valgrindFailed":false,"points":["p01-09.1"],"exception":["  File \"/home/nikolai/anaconda3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n","  File \"/home/nikolai/anaconda3/lib/python3.7/unittest/case.py\", line 628, in run\n    testMethod()\n","  File \"/home/nikolai/Documents/learning/datascience_mooc/exercises/tmcdata/TMC workspace/Exercises/hy/hy-data-analysis-with-python-2020/part01-e09_merge/test/test_merge.py\", line 47, in test_random\n    self.assertEqual(len(result), len(L), msg\u003d\"Incorrect length of result list for input lists %s and %s!\" % (L1, L2))\n","  File \"/home/nikolai/anaconda3/lib/python3.7/unittest/case.py\", line 852, in assertEqual\n    assertion_func(first, second, msg\u003dmsg)\n","  File \"/home/nikolai/anaconda3/lib/python3.7/unittest/case.py\", line 845, in _baseAssertEqual\n    raise self.failureException(msg)\n"]}],"logs":{}}